"use client";

import React from "react";
import { RotateCcw, AlertTriangle, X } from "lucide-react";

interface RollbackModalProps {
  isOpen: boolean;
  onConfirm: () => void;
  onClose: () => void;
  taskTitle?: string;
}

export const RollbackModal: React.FC<RollbackModalProps> = ({
  isOpen,
  onConfirm,
  onClose,
  taskTitle = "Current task",
}) => {
  if (!isOpen) return null;

  return (
    <div className="modal-overlay" role="dialog" aria-modal="true" aria-label="Confirm Rollback">
      <div className="modal-dialog">
        <div style={{ padding: "16px 20px", background: "rgba(239, 68, 68, 0.08)", borderBottom: "1px solid rgba(239, 68, 68, 0.2)", display: "flex", alignItems: "center", gap: "10px" }}>
          <div style={{ width: "32px", height: "32px", borderRadius: "var(--radius-sm)", background: "rgba(239, 68, 68, 0.15)", color: "var(--color-error)", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <RotateCcw size={18} />
          </div>
          <div>
            <h3 style={{ fontSize: "14px", fontWeight: 700, color: "var(--text-primary)" }}>
              RESTORE PREVIOUS REPOSITORY STATE?
            </h3>
            <p style={{ fontSize: "12px", color: "var(--text-secondary)" }}>
              Revert uncommitted modifications back to the baseline Git commit.
            </p>
          </div>
        </div>

        <div style={{ padding: "20px" }}>
          <p style={{ fontSize: "13px", color: "var(--text-secondary)", lineHeight: 1.5 }}>
            This action will discard all file edits, created files, and test artifacts generated by{" "}
            <strong style={{ color: "var(--text-primary)" }}>{taskTitle}</strong>.
          </p>
          <div style={{ marginTop: "12px", padding: "10px 12px", background: "var(--bg-secondary)", borderRadius: "var(--radius-sm)", border: "1px solid var(--border-subtle)", fontSize: "12px", color: "var(--text-muted)", display: "flex", alignItems: "center", gap: "8px" }}>
            <AlertTriangle size={14} color="var(--color-warning)" />
            <span>Files modified outside of CodeForge AI prior to this run will be preserved.</span>
          </div>
        </div>

        <div style={{ padding: "12px 20px", background: "var(--bg-secondary)", borderTop: "1px solid var(--border-default)", display: "flex", alignItems: "center", justifyContent: "flex-end", gap: "10px" }}>
          <button className="btn btn-secondary" onClick={onClose}>
            Cancel
          </button>
          <button className="btn btn-danger" onClick={onConfirm}>
            <RotateCcw size={13} />
            <span>Confirm & Restore</span>
          </button>
        </div>
      </div>
    </div>
  );
};
