from pathlib import Path
from typing import List, Dict
from app.schemas.agent import ImplementationPlan, CodeGenerationResult
from app.services.llm_provider import llm_provider
from app.tools.filesystem import read_file, create_file
from app.tools.patch_engine import PatchApplier, PatchValidator, PatchRollback

class CodingAgent:
    """
    Autonomous code generation agent. Synthesizes surgical code modifications,
    validates syntax and security boundaries, and applies patches to the workspace.
    """
    async def implement_plan(
        self,
        workspace_dir: Path,
        plan: ImplementationPlan,
        task_prompt: str,
        repo_summary: dict | None = None
    ) -> List[str]:
        modified_files: List[str] = []
        rollback = PatchRollback(workspace_dir)

        # 1. Handle explicit files to create
        for fpath in plan.files_to_create:
            target = workspace_dir / fpath
            if not target.exists():
                create_file(workspace_dir, fpath, f"# Generated by CodeForge AI for: {task_prompt}\n")
                modified_files.append(fpath)

        # 2. Gather context of files to modify
        file_contexts: Dict[str, str] = {}
        for fpath in plan.files_to_modify:
            try:
                rollback.capture(fpath)
                file_contexts[fpath] = read_file(workspace_dir, fpath)
            except Exception as e:
                print(f"[CodingAgent] Warning reading context for {fpath}: {e}")

        # 3. Call real LLM code generation engine
        code_result: CodeGenerationResult = await llm_provider.generate_code_patch(
            task_prompt=task_prompt,
            plan=plan,
            relevant_files_context=file_contexts,
            repo_summary=repo_summary or {}
        )

        # 4. Validate and apply generated patches
        for patch in code_result.patches:
            try:
                if patch.patch_type == "replace" and patch.full_content is not None:
                    PatchApplier.apply_replacement(
                        workspace_dir=workspace_dir,
                        relative_path=patch.file_path,
                        new_content=patch.full_content,
                        validate_syntax=True
                    )
                    if patch.file_path not in modified_files:
                        modified_files.append(patch.file_path)
                elif patch.patch_type == "hunk" and patch.old_hunk and patch.new_hunk:
                    PatchApplier.apply_hunk(
                        workspace_dir=workspace_dir,
                        relative_path=patch.file_path,
                        old_hunk=patch.old_hunk,
                        new_hunk=patch.new_hunk,
                        validate_syntax=True
                    )
                    if patch.file_path not in modified_files:
                        modified_files.append(patch.file_path)
            except Exception as e:
                print(f"[CodingAgent] Failed applying patch to {patch.file_path}: {e}. Rolling back...")
                rollback.rollback_all()
                raise e

        return modified_files

coding_agent = CodingAgent()
